const cardsInfo = [
    {
      id: 1,
      name: 'Multi-Post Stories Gain+Glory',
      name1: 'Keeping Track of Hundred of Components',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s.',
      technologies: {
        tech1: 'Ruby on Rails',
        tech2: 'CSS',
        tech3: 'JavaScript',
      },
      liveLink: '#',
      sourceLink: '#',
    },
    {
      id: 2,
      name: 'Multi-Post Stories Gain+Glory',
      name1: 'Keeping Track of Hundred of Components',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s.',
      technologies: {
        tech1: 'Ruby on Rails',
        tech2: 'CSS',
        tech3: 'JavaScript',
        tech4: 'HTML',
      },
      liveLink: '#',
      sourceLink: '#',
    },
    {
      id: 3,
      name: 'Multi-Post Stories Gain+Glory',
      name1: 'Keeping Track of Hundred of Components',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s.',
      technologies: {
        tech1: 'Ruby on Rails',
        tech2: 'CSS',
        tech3: 'JavaScript',
        tech4: 'HTML',
      },
      liveLink: '#',
      sourceLink: '#',
    },
    {
      id: 4,
      name: 'Multi-Post Stories Gain+Glory',
      name1: 'Keeping Track of Hundred of Components',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s.',
      technologies: {
        tech1: 'Ruby on Rails',
        tech2: 'CSS',
        tech3: 'JavaScript',
        tech4: 'HTML',
      },
      liveLink: '#',
      sourceLink: '#',
    },
    {
      id: 5,
      name: 'Multi-Post Stories Gain+Glory',
      name1: 'Keeping Track of Hundred of Components',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s.',
      technologies: {
        tech1: 'Ruby on Rails',
        tech2: 'CSS',
        tech3: 'JavaScript',
        tech4: 'HTML',
      },
      liveLink: '#',
      sourceLink: '#',
    },
    {
      id: 6,
      name: 'Multi-Post Stories Gain+Glory',
      name1: 'Keeping Track of Hundred of Components',
      description: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it 1960s.',
      technologies: {
        tech1: 'Ruby on Rails',
        tech2: 'CSS',
        tech3: 'JavaScript',
        tech4: 'HTML',
      },
      liveLink: '#',
      sourceLink: '#',
    },
    // Add more project objects as needed
  ];
